### ISSUE TITLE
Touch Screen

### ISSUE THREAD

**Issue by wu-hongjun** [zysuper/Thinkpad-X1-extreme-EFI#2]
Hi,

On my machine, I simply used the USBInjectAll.kext and the XHCI patch for injecting all usb ports and it works well. Maybe it's a good thing to try to inject as many ports as possible.

**Comment by zysuper** [comment]
I used fb-patcher to remove all invalid usb interfaces, including blocking the built-in Bluetooth interface (because he can't work effectively), so there is no need to use the USBInjectAll.kext and usb ports limited patch. For usb port configuration please see usbports.kext.
XHCI-unsupported.kext is need by all 300 series Vendor Id is 0x8086, Device Id is 0xA36D XHC usb controller.

**Comment by andyy24** [comment]
都是中国人用英文交流不累吗?

**Comment by wu-hongjun** [comment]
Sometimes other people who don't know about Chinese wants to research for solutions. (Excuse. Mainly because I am using someone else's laptop without a Chinese keyboard 2333333)
